[versions]
agp = "8.13.2"
wear = "1.3.0"


[libraries]
androidx-wear = { group = "androidx.wear", name = "wear", version.ref = "wear" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

